# Generated by Django 4.2.19 on 2025-04-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0006_alter_visionpanel_scenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='visionpanel',
            name='property',
            field=models.JSONField(default=dict, verbose_name='通用属性列'),
        ),
    ]
