# Generated by Django 4.2.19 on 2025-04-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0024_auto_20250307_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='processapplication',
            name='property',
            field=models.JSONField(default=dict, verbose_name='通用属性列'),
        ),
        migrations.AddField(
            model_name='riskexperience',
            name='property',
            field=models.JSONField(default=dict, verbose_name='通用属性列'),
        ),
        migrations.AddField(
            model_name='riskrule',
            name='property',
            field=models.JSONField(default=dict, verbose_name='通用属性列'),
        ),
    ]
