# Generated by Django 4.2.19 on 2025-04-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databus', '0019_collectorplugin_has_replica_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectorconfig',
            name='property',
            field=models.JSONField(default=dict, verbose_name='通用属性列'),
        ),
        migrations.AddField(
            model_name='collectorplugin',
            name='property',
            field=models.JSONField(default=dict, verbose_name='通用属性列'),
        ),
        migrations.AddField(
            model_name='redisconfig',
            name='property',
            field=models.JSONField(default=dict, verbose_name='通用属性列'),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='property',
            field=models.JSONField(default=dict, verbose_name='通用属性列'),
        ),
    ]
